'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Fronteira.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Adicionar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Adicionar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property Adicionar21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Adicionar21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property AlertaAlarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlertaAlarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property branco() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("branco", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property Excluir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Excluir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property excluir_chave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluir_chave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Excluir2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Excluir2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property expandido() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("expandido", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property expandir() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("expandir", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Public ReadOnly Property impressora() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("impressora", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Limpar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Limpar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property loading() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loading", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Lupa() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Lupa", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property segtrab() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("segtrab", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property validar_chave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("validar_chave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property validar_chave1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("validar_chave1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
